### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'pkey'

### ISSUE THREAD

**Issue by patrick91** [FriendCode/gittle#18]
Hi, this is the stacktrace:

```
>>> from gittle import Gittle
>>> from gittle import GittleAuth
>>> 
>>> k = open('/tmp/tmp_rsa')
>>> url = 'https://github.com/patrick91/fROLLino-ftw.git'
>>> auth = GittleAuth(pkey=k)
>>> Gittle.clone(url, '/tmp/testclone', auth=auth)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/patrick91/.virtualenvs/gittle/lib/python2.7/site-packages/gittle/gittle.py", line 438, in clone
    repo.fetch(bare=bare)
  File "/Users/patrick91/.virtualenvs/gittle/lib/python2.7/site-packages/gittle/gittle.py", line 405, in fetch
    remote_refs = self.fetch_remote(origin_uri)
  File "/Users/patrick91/.virtualenvs/gittle/lib/python2.7/site-packages/gittle/gittle.py", line 362, in fetch_remote
    client, remote_path = self.get_client(origin_uri=origin_uri)
  File "/Users/patrick91/.virtualenvs/gittle/lib/python2.7/site-packages/gittle/gittle.py", line 326, in get_client
    client, remote_path = get_transport_and_path(origin_uri, **client_kwargs)
  File "/Users/patrick91/.virtualenvs/gittle/lib/python2.7/site-packages/dulwich/client.py", line 981, in get_transport_and_path
    return HttpGitClient(urlparse.urlunparse(parsed), **kwargs), parsed.path
  File "/Users/patrick91/.virtualenvs/gittle/lib/python2.7/site-packages/dulwich/client.py", line 829, in __init__
    GitClient.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'pkey'
```

I tried to do some fixes, but nothing worked.

This is the output of pip freeze:

```
GDAL==1.10.0
Pygments==1.6
bpython==0.12
dulwich==0.9.3
funky==0.0.2
gittle==0.2.2
libxml2-python==2.9.1
mimer==0.0.1
paramiko==1.10.0
pycrypto==2.6
```

**Comment by remy1991** [comment]
Is anybody still getting this issue ? 
I am using gittle (0.5.0) and the issue seems to be still there.

**Comment by killkill** [comment]
dulwich==0.9.8
gittle==0.5.0
has the same problem

**Comment by pwhack** [comment]
dulwich (0.10.0)
gittle (0.5.0)
still has problem. in my case, however, i'm using username and password combo in GittleAuth and getting:
TypeError: __init__() got an unexpected keyword argument 'username'

**Comment by DoubleSpout** [comment]
I have the same problem below:

    TypeError: __init__() got an unexpected keyword argument 'pkey'

finally i solved it !!!!!
@8427003 thanks for your help.

1、remove all dulwich
2、download [dulwich-0.9.1-2](https://github.com/AaronO/dulwich/tarball/eebb032b2b7b982d21d636ac50b6e45de58b208b#egg=dulwich-0.9.1-2)
3、install the dulwich-0.9.1-2
    
    python setup.py --pure install

4、you will meet `refs.py not found error` and `not found git_line error`
5、download [dulwich](https://github.com/AaronO/dulwich/archive/master.zip), copy `refs.py` and `objects.py` into `site-packages/dulwich-0.9.1-py2.7.egg/dulwich/`  
6、Then it works !

**Comment by natlibfi-arlehiko** [comment]
Here's what worked for me:

1. `pip uninstall dulwich`
2. `pip install https://github.com/AaronO/dulwich/tarball/eebb032b2b7b982d21d636ac50b6e45de58b208b#egg=dulwich-0.9.1-2`
3. `curl -o /usr/local/lib/python2.7/dist-packages/dulwich/refs.py https://raw.githubusercontent.com/jelmer/dulwich/dulwich-0.9.7/dulwich/refs.py`
