### ISSUE TITLE
CRITICAL License issue

### ISSUE THREAD

**Issue by philippe-goetz** [FriendCode/gittle#24]
The project gittle is licensed as Apache 2.0, but imports "dulwich" package, which is GPL v2 (see http://git.samba.org/?p=jelmer/dulwich.git;a=blob_plain;f=COPYING;hb=HEAD). In order to avoid license break, please reconsider gittle license and reassign its license to GPL v2.

gittle as well as dulwich cannot be used (meaning imported) in proprietary projects (or in general in non GPL projects).

This is a known issue more information http://www.apache.org/licenses/GPL-compatibility.html.

**Comment by jelmer** [comment]
FWIW Dulwich has been relicensed to dual Apache License, version 2 o/GNU GPLv2. This should address the license compatibility issues with Gittle.

**Comment by jelmer** [comment]
Can somebody close this?

**Comment by AaronO** [comment]
@jelmer Thanks for bumping, closed.
