### ISSUE TITLE
Tagging versions

### ISSUE THREAD

**Issue by milesj** [FriendCode/gittle#56]
Don't see anywhere in the source code or the docs for creating tags. This would be really useful.

**Comment by AaronO** [comment]
@milesj That took a bit longer, I added a bunch of other small improvements and fixes such as `dwim_reference`.

You can now:

### Resolve a tag :

```py
In [1]: from gittle import Gittle
In [2]: repo = Gittle('.')
In [3]: repo['0.0.1']
Out[3]: <Commit c00ba7e938c6081677be146da6582f2cc827f190>
```

### Create a tag

```py
repo.create_tag("0.1.0", "master")
```

### Remove tag

```py
repo.remove_tag("0.1.0")
```

or

```py
del repo["0.1.0"]
```

**Comment by milesj** [comment]
Very awesome! Thanks for the quick turn around.

**Comment by milesj** [comment]
This worked pretty well: https://github.com/titon/framework/blob/master/bin/split-packages#L179

Just one question. How would I push the tags? Since `repo.push()` doesn't seem to do it as I'm assuming the `--tags` option isn't being passed.
