### ISSUE TITLE
incorrect parsing

### ISSUE THREAD

**Issue by amit2555** [FriendCode/gittle#59]
It seems the diff output is not showing any text after the line '@@ blah blah @@' <text_missing>.
It shows the text from the next line.

**Comment by AaronO** [comment]
There is indeed an extra `\n \n` that is inserted, however that's done by `dulwich`.

All you would need to do is simply patch that string (`.replace('@@\n \n', '@@ ')`)

That should give you the same result as git.

**Comment by jelmer** [comment]
On Tue, Jan 20, 2015 at 08:15:38AM -0800, AaronO wrote:
> There is indeed an extra `\n \n` that is inserted, however that's done by `dulwich`.
> 
> All you would need to do is simply patch that string (`.replace('@@\n \n', '@@ ')`)
> 
> That should give you the same result as git.

This bug report appears to be missing some context; where is dulwich
inserting another newline?

Jelmer

**Comment by AaronO** [comment]
@jelmer Gittle is using `dulwich`'s `patch` module (https://github.com/FriendCode/gittle/blob/master/gittle/utils/git.py#L91).

I'm not 100% sure about the `\n \n` that's simply what I saw in my simple test, but a newline is definitely inserted by `unified_diff` (here: https://github.com/jelmer/dulwich/blob/master/dulwich/patch.py#L92).

That's not necessarily a big problem, but it's not exactly what `git log` returns as per @amit2555's question.

**Comment by jelmer** [comment]
On Tue, Jan 20, 2015 at 12:14:02PM -0800, AaronO wrote:
> @jelmer Gittle is using `dulwich`'s `patch` module (https://github.com/FriendCode/gittle/blob/master/gittle/utils/git.py#L91).
> 
> I'm not 100% sure about the `\n \n` that's simply what I saw in my simple test, but a newline is definitely inserted by `unified_diff` (here: https://github.com/jelmer/dulwich/blob/master/dulwich/patch.py#L92).
That's only inserting a single new-line though, not two.

This code is also exercised by 'dulwich show', which doesn't appear to
be inserting extra newlines.

Is gittle perhaps adding newlines when combining the strings returned
by unified_diff() ?

Cheers,

Jelmer
