### ISSUE TITLE
Dulwich uses GPLv2 license

### ISSUE THREAD

**Issue by bjoernricks** [FriendCode/gittle#7]
Hi,

you are using dulwich which is licensed under the GPLv2 (https://github.com/jelmer/dulwich/blob/master/COPYING).  Therefore gittle could be considered as derived work as stated in the GPL license (https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works). As a final consequence gittle must be licensed under the GPLv2 too. I am not a lawyer so please understand this issue just as a hint.

**Comment by jelmer** [comment]
FWIW the relicense has happened; dulwich 0.15.0 is dual Apache-2 / GPL-2+
