### ISSUE TITLE
get one file

### ISSUE THREAD

**Issue by richarddevers** [FriendCode/gittle#86]
Hello gittle team!

Is there a way to get only one file of one specific branch?

Thanks,

regards

**Comment by jelmer** [comment]
I'm not sure if this functionality is exposed in gittle, but Dulwich (which gittle uses for heavy-lifting) can do this. See http://www.aaronheld.com/post/using-python-dulwich-to-load-any-version-of-a-file-from-a-local-git-repo

**Comment by richarddevers** [comment]
Ok, thanks for your reply!
